### ISSUE TITLE
json: cannot unmarshal string into Go struct field ItemResponse.additional_info.items.quantity of type int

### ISSUE THREAD

**Issue by butaca** [mercadopago/sdk-go#38]
When calling payment.Client.Get I get the error "json: cannot unmarshal string into Go struct field itemResponse.additional_info.items.quantity of type int".

100% repro
go 1.22.0
github.com/mercadopago/sdk-go v0.0.0-20240313185426-6f3af8beb59f

**Comment by gdeandradero** [comment]
Fixed by https://github.com/mercadopago/sdk-go/pull/39.
