### ISSUE TITLE
unmarshal errors when calling payment.Client.Get

### ISSUE THREAD

**Issue by butaca** [mercadopago/sdk-go#40]
Hi, It's me again... sorry. I'm reporting a similar error to #38 but with other fields when calling payment.Client.Get. This time I fixed locally one by one, getting error after error, until success.

All the errors I found so far:

* "json: cannot unmarshal string into Go struct field ItemResponse.additional_info.items.unit_price of type float64".
* "json: cannot unmarshal string into Go struct field OrderResponse.order.id of type int"

go version go1.22.0 darwin/arm64
github.com/mercadopago/sdk-go v0.0.0-20240314131414-b9fd995267f8

**Comment by gdeandradero** [comment]
Hello, thanks again 😅.
Fixed it.
