### ISSUE TITLE
 payment.NewClient

### ISSUE THREAD

**Issue by oscarict** [mercadopago/sdk-go#56]
I'm implement the Go SDK but when try make payment using PSE we go this error
json: cannot unmarshal number into Go struct field TransactionDetailsResponse.transaction_details.bank_transfer_id of type string

Our Code
accessToken := "TEST-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
		cfg, err := config.New(accessToken)
		if err != nil {
			fmt.Println(err)
			return err
		}

		client := payment.NewClient(cfg)
		request := payment.Request{
			TransactionAmount: 500000,
			Description:       "pago realizo pago del pago",
			PaymentMethodID:   "pse",
			Payer: &payment.PayerRequest{
				Email:      "oscar@emailfake.com",
				EntityType: "individual",
				Identification: &payment.IdentificationRequest{
					Type:   "CC",
					Number: "98666222",
				},
				Address: &payment.AddressRequest{
					ZipCode:      "111",
					StreetName:   "Siempre viva",
					StreetNumber: "111",
					Neighborhood: "Sarasa",
					City:         "Medellín",
					FederalUnit:  "1",
				},
				Phone: &payment.PhoneRequest{
					AreaCode: "011",
					Number:   "333333333",
				},
			},
			AdditionalInfo:     &payment.AdditionalInfoRequest{IPAddress: "127.0.0.1"},
			TransactionDetails: &payment.TransactionDetailsRequest{FinancialInstitution: "1303"},
			CallbackURL:        "http://www.your-site.com",
		}

		resource, err := client.Create(context.Background(), request)
		if err != nil {
			fmt.Println("!")
			fmt.Println(err)
			return err
		}

Response
json: cannot unmarshal number into Go struct field TransactionDetailsResponse.transaction_details.bank_transfer_id of type string

![image](https://github.com/mercadopago/sdk-go/assets/100735351/61ea41a2-476d-4d81-baff-f1d1be17b4e7)

**Comment by gdeandradero** [comment]
Hello, we fixed it, sorry for the inconvenience.
