### ISSUE TITLE
unmarshal errors when calling payment.Client.Get

### ISSUE THREAD

**Issue by marvin-w** [mercadopago/sdk-go#61]
I get the following error when I try to get a payment via the SDK:

`json: cannot unmarshal number into Go struct field Response.differential_pricing_id of type string`

Probably related to: https://github.com/mercadopago/sdk-go/blob/main/pkg/payment/response.go#L26

**Comment by andreagostinho-meli** [comment]
Hello @marvin-w, I'm analyzing your issue.

**Comment by marvin-w** [comment]
Any update? I even opened a PR to fix this.

**Comment by andreagostinho-meli** [comment]
@marvin-w hi! sorry for the delay.
Please, do you have a Payment ID generated during your testing that you can share with us?

I will merge your PR and release a new version of the Go SDK soon to fix the unmarshal error.
But, for your information, analyzing the field `differential_pricing_id` internally, I found it is actually deprecated and should not be used.
We will also soon open a PR to mark that field as deprecated in our SDKs.

**Comment by andreagostinho-meli** [comment]
@marvin-w the fix was released in v1.0.2: https://pkg.go.dev/github.com/mercadopago/sdk-go@v1.0.2.
Thanks for your contribution!
