### ISSUE TITLE
Transfer to CBU/CVU/ALIAS?

### ISSUE THREAD

**Issue by ezequielaguilera1993** [mercadopago/sdk-go#68]
Why doesn't Mercado Pago provide a method to make bank transfers from your own account to another CBU/CVU/ALIAS?

Thanks :)

**Comment by danielen-meli** [comment]
Hi @ezequielaguilera1993, 

Thank you very much for contacting us!
We will analyze your request and, if it makes sense, add it to our backlog so that it can be implemented.
If you wish to contribute directly to the code, we also accept contributions in the format of Pull Requests.

**Comment by ezequielaguilera1993** [comment]
would like to contribute, but I understand that this library makes HTTP calls to the endpoints provided by Mercado Pago in its base API.
And I can't find which endpoint is necessary for account-to-account transfers (without a card). And if it exists.
If it exists, I have no problem adding the functionality to the SDK.
Regards.

P.S. I was thinking that if the same Mercado Pago card is used, it would be like an account-to-account transfer. But I wouldn't know how to configure it.

P.S.2. Vamos Messi carajo
