### ISSUE TITLE
BankInfoResponse type error

### ISSUE THREAD

**Issue by jonathastavares** [mercadopago/sdk-go#72]
Hey folks!

I found a little bug with BankInfoResponse type.

The property `IsSameBankAccountOwner` is typed as `String`, but payment.Client.Get returns a bool, and then unmarshal fails.

Simply changed the property type to `bool` to fix it.

**Comment by andreagostinho-meli** [comment]
@jonathastavares thanks for your report!
I'm working on the solution.

**Comment by andreagostinho-meli** [comment]
Hello @jonathastavares, the fix was released in [`v1.0.5`](https://github.com/mercadopago/sdk-go/releases/tag/v1.0.5).
Thank you!
